/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_epsilony_simpmeshfree_model_TriangleJni */

#ifndef _Included_net_epsilony_simpmeshfree_model_TriangleJni
#define _Included_net_epsilony_simpmeshfree_model_TriangleJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_epsilony_simpmeshfree_model_TriangleJni
 * Method:    triangleFun
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_net_epsilony_simpmeshfree_model_TriangleJni_triangleFun
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
